### 获取8088用户信息
GET http://localhost:8088/api/?id=101

### 获取超时信息
GET http://localhost:8088/find/?timeout=1100

### 修改灰度比例值
GET http://localhost:8088/gray/?ratio=80

### 更改超时端口
GET http://localhost:8081/ports?ports=8080,8094


### 获取用户信息
POST http://localhost:8088/
Content-Type: application/json

{
  "service": "com.ipoca.bbrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [100]
}


### 获取订单信息
POST http://localhost:8082/
Content-Type: application/json

{
  "service": "com.ipoca.bbrpc.demo.api.UserService",
  "methodSign": "findById@2_int_java.lang.String",
  "args": [200,"bb"]
}

### mock
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "com.ipoca.bbrpc.demo.api.UserService",
  "method": "toString",
  "args": []
}

###
