server:
  port: 8081

bbrpc:
  zk:
    server: localhost:2181
    root: bbrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      tc: 25
bbregistry:
  servers: http://localhost:8084

logging:
  level:
    root: error
    com.ipoca.bbrpc: info

app:
  id: app1
apollo:
  cacheDir: /opt/data/
  cluster: default
  meta: http://kimmking.cm:8070
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: ipoca
    eagerLoad:
      enabled: false
