server:
  port: 8081

app:
  id: app1
  namespace: public
  env: dev
  metas: "{dc: 'bj', gray: 'false', unit: 'B001'}"


bbrpc:
  zkServer: localhost:2181
  zkRoot: bbrpc

logging:
  level:
    root: error
    com.ipoca.bbrpc: info
