server:
  port: 8088

bbrpc:
#  static:
#    providers: http://localhost:8081,http://localhost:8082,http://localhost:8083
  zk:
    server: localhost:2181
    root: bbrpc
  app:
    id: app1
    namespace: public
    env: dev
  consumer:
    retries: 2
    timeout: 10000
    grayRatio: 33 # 0-100
    faultLimit: 10 # 30s 内10次错误则隔离
    halfOpenInitialDelay: 10000
    halfOpenDelay: 60000

logging:
  level:
    root: error
    com.ipoca.bbrpc: debug
